version: '3'

services:
  cv_pipeliner_app:
    image: eu.gcr.io/e8-gke/cv-pipeliner-app:0.6.0
    container_name: "cv_pipeliner_app"
    ports:
      - "8050:8050"
    environment:
      CV_PIPELINER_APP_CONFIG: /configs/my_config_brickit_gcs.yaml
      HOST: 0.0.0.0
      PORT: 8050
      FLASK_ENV: development
    volumes:
      - ./configs/:/configs/
      - ~/.config/gcloud:/root/.config/gcloud

    command: ["python", "apps/app/app_dash.py"]

  cv_pipeliner_dataset_browser:
    image: eu.gcr.io/e8-gke/cv-pipeliner-app:0.6.0
    container_name: "dataset_browser"
    ports:
      - "8051:8051"
    environment:
      CV_PIPELINER_APP_CONFIG: /configs/my_config_brickit_gcs.yaml
      HOST: 0.0.0.0
      PORT: 8051
      FLASK_ENV: development
    volumes:
      - ./configs/:/configs/
      - ~/.config/gcloud:/root/.config/gcloud
    command: ["python", "apps/dataset_browser/app_dash.py"]
