{{- $window := .Values.kfserving.knativeWindow -}}
{{ range .Values.kfserving.models }}
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: {{ .name }}
  annotations:
    autoscaling.knative.dev/window: "{{ $window }}"
spec:
  default:
    predictor:
      maxReplicas: 1
      minReplicas: 0
      tensorflow:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
            nvidia.com/gpu: "1"
        runtimeVersion: 2.4.1-gpu
        storageUri: {{ .storageUri }}
---
{{ end }}