apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.app-name" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
