{{- if .Values.virtualService.enabled }}
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: {{ .Values.virtualService.uri }}
      rewrite:
        uri: /
      route:
        - destination:
            host: "{{ include "helm-chart.app-name" . }}.{{ .Release.Namespace }}.svc.cluster.local"
            port:
              number: {{ .Values.service.port }}
      timeout: 300s
{{- end }}
