backend:
    url: 'http://localhost:5000/'

data:
    base_labels_images_dir: 'renders/'
    labels_decriptions: 'label_to_description.json'

    images_dirs:
        - 'images_dir_with_annotation/':
            - 'annotations_filename.json'
        - 'images_dir_without_annotation/': []
    images_annotation_type: 'supervisely'  # 'supervisely', 'brickit'

    videos_dirs:
        - 'videos_dir1'

    minimum_iou: 0.5
